baseURL = "https://armando.ooo/"
languageCode = "en-us"
title = "Armando Orozco"
theme="archie"
copyright = "Â© Armando Orozco"
license = "MIT"
licenselink = "https://github.com/athul/archie/blob/master/LICENSE"


pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Hi welcome to my page I will post discoveries or things new stuff I have learned here :) "

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/armando013005"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3